// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.9
// source: api/grpc/proto/url_shortener.proto

package grpc_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullUrl string `protobuf:"bytes,1,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`
}

func (x *ShortenUrlRequest) Reset() {
	*x = ShortenUrlRequest{}
	mi := &file_api_grpc_proto_url_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenUrlRequest) ProtoMessage() {}

func (x *ShortenUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_url_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenUrlRequest.ProtoReflect.Descriptor instead.
func (*ShortenUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_url_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenUrlRequest) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

type ShortenUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortenUrlResponse) Reset() {
	*x = ShortenUrlResponse{}
	mi := &file_api_grpc_proto_url_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenUrlResponse) ProtoMessage() {}

func (x *ShortenUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_url_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenUrlResponse.ProtoReflect.Descriptor instead.
func (*ShortenUrlResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_url_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenUrlResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type UnshortenUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *UnshortenUrlRequest) Reset() {
	*x = UnshortenUrlRequest{}
	mi := &file_api_grpc_proto_url_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnshortenUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnshortenUrlRequest) ProtoMessage() {}

func (x *UnshortenUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_url_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnshortenUrlRequest.ProtoReflect.Descriptor instead.
func (*UnshortenUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_url_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *UnshortenUrlRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type UnshortenUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullUrl string `protobuf:"bytes,1,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`
}

func (x *UnshortenUrlResponse) Reset() {
	*x = UnshortenUrlResponse{}
	mi := &file_api_grpc_proto_url_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnshortenUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnshortenUrlResponse) ProtoMessage() {}

func (x *UnshortenUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_url_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnshortenUrlResponse.ProtoReflect.Descriptor instead.
func (*UnshortenUrlResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_url_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *UnshortenUrlResponse) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

var File_api_grpc_proto_url_shortener_proto protoreflect.FileDescriptor

var file_api_grpc_proto_url_shortener_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x22, 0x2e, 0x0a, 0x11, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55,
	0x72, 0x6c, 0x22, 0x31, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x32, 0x0a, 0x13, 0x55, 0x6e, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x31, 0x0a, 0x14, 0x55, 0x6e, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x75, 0x6c, 0x6c, 0x55, 0x72, 0x6c, 0x32, 0xb6, 0x01, 0x0a,
	0x0c, 0x55, 0x72, 0x6c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x4f, 0x0a,
	0x0a, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x1f, 0x2e, 0x75, 0x72,
	0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x75,
	0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55,
	0x0a, 0x0c, 0x55, 0x6e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x21,
	0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x55, 0x6e,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x2e, 0x55, 0x6e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_proto_url_shortener_proto_rawDescOnce sync.Once
	file_api_grpc_proto_url_shortener_proto_rawDescData = file_api_grpc_proto_url_shortener_proto_rawDesc
)

func file_api_grpc_proto_url_shortener_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_url_shortener_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_proto_url_shortener_proto_rawDescData)
	})
	return file_api_grpc_proto_url_shortener_proto_rawDescData
}

var file_api_grpc_proto_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_grpc_proto_url_shortener_proto_goTypes = []any{
	(*ShortenUrlRequest)(nil),    // 0: urlshortener.ShortenUrlRequest
	(*ShortenUrlResponse)(nil),   // 1: urlshortener.ShortenUrlResponse
	(*UnshortenUrlRequest)(nil),  // 2: urlshortener.UnshortenUrlRequest
	(*UnshortenUrlResponse)(nil), // 3: urlshortener.UnshortenUrlResponse
}
var file_api_grpc_proto_url_shortener_proto_depIdxs = []int32{
	0, // 0: urlshortener.UrlShortener.ShortenUrl:input_type -> urlshortener.ShortenUrlRequest
	2, // 1: urlshortener.UrlShortener.UnshortenUrl:input_type -> urlshortener.UnshortenUrlRequest
	1, // 2: urlshortener.UrlShortener.ShortenUrl:output_type -> urlshortener.ShortenUrlResponse
	3, // 3: urlshortener.UrlShortener.UnshortenUrl:output_type -> urlshortener.UnshortenUrlResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_url_shortener_proto_init() }
func file_api_grpc_proto_url_shortener_proto_init() {
	if File_api_grpc_proto_url_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_proto_url_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_proto_url_shortener_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_url_shortener_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_url_shortener_proto_msgTypes,
	}.Build()
	File_api_grpc_proto_url_shortener_proto = out.File
	file_api_grpc_proto_url_shortener_proto_rawDesc = nil
	file_api_grpc_proto_url_shortener_proto_goTypes = nil
	file_api_grpc_proto_url_shortener_proto_depIdxs = nil
}
